[Launch]
; Masukkan nama file EXE asli di sini.
; File ini WAJIB ada di dalam folder App\GlickkoApp
ProgramExecutable=Photoshop.exe

[Branding]
; Nama ini hanya untuk identitas (Opsional)
AppName=Adobe Photoshop 2024 Portable